"""
WebSocket Manager for the AI Proctoring Backend.

Manages active WebSocket connections, origin validation, message broadcasting,
and heartbeat monitoring. Supports multiple simultaneous connections per session.

Requirements: 11.1, 11.2, 11.6, 11.7, 11.8, 11.9
"""

from __future__ import annotations

import asyncio
import logging
import time
from typing import Dict, List, Optional

from fastapi import WebSocket, WebSocketDisconnect

from app.core import security

logger = logging.getLogger(__name__)

# Heartbeat configuration
HEARTBEAT_INTERVAL_S: float = 30.0
PONG_TIMEOUT_S: float = 10.0


class WebSocketManager:
    """Manages WebSocket connections for the AI Proctoring Backend.

    Maintains two registries:
    - ``_connections``: maps ``session_id`` → list of active ``WebSocket`` objects.
    - ``_conn_to_session``: maps ``connection_id`` → ``session_id`` for reverse lookup.

    Provides methods to connect, disconnect, broadcast, and send targeted messages.
    Also runs a background heartbeat coroutine that pings all clients every 30 seconds
    and disconnects clients that have not responded within 10 seconds.

    Attributes:
        _connections: Registry of session_id → list of WebSocket connections.
        _conn_to_session: Registry of connection_id → session_id.
        _conn_to_ws: Registry of connection_id → WebSocket for direct lookup.
        _last_pong: Tracks the last pong timestamp (monotonic) per connection_id.
        _lock: Asyncio lock protecting all registry mutations.
    """

    def __init__(self) -> None:
        self._connections: Dict[str, List[WebSocket]] = {}
        self._conn_to_session: Dict[str, str] = {}
        self._conn_to_ws: Dict[str, WebSocket] = {}
        self._last_pong: Dict[str, float] = {}
        self._lock: asyncio.Lock = asyncio.Lock()

    async def connect(
        self,
        websocket: WebSocket,
        session_id: str,
        connection_id: str,
        origin: str,
        allowed_origins: List[str],
    ) -> None:
        """Accept and register a new WebSocket connection after origin validation.

        Validates the ``Origin`` header against ``allowed_origins`` using
        :func:`app.core.security.validate_origin`. If the origin is not allowed,
        the WebSocket is closed with code ``4003`` (Forbidden) and the method
        returns without registering the connection.

        If the origin is valid, the connection is registered in both
        ``_connections`` (keyed by ``session_id``) and ``_conn_to_session``
        (keyed by ``connection_id``), and the WebSocket is accepted.

        Args:
            websocket: The incoming FastAPI ``WebSocket`` instance.
            session_id: The proctoring session identifier from the URL path.
            connection_id: A unique identifier for this specific connection
                (e.g. a UUID generated by the router).
            origin: The value of the ``Origin`` header from the upgrade request.
            allowed_origins: The list of permitted origins from ``Config.CORS_ORIGINS``.

        Returns:
            None. The WebSocket is either accepted or closed with 4003.
        """
        if not security.validate_origin(origin, allowed_origins):
            logger.warning(
                "WebSocket connection rejected: disallowed origin",
                extra={
                    "session_id": session_id,
                    "connection_id": connection_id,
                    "origin": origin,
                    "action": "reject",
                },
            )
            # Must accept before closing with a custom code
            await websocket.accept()
            await websocket.close(code=4003)
            return

        async with self._lock:
            if session_id not in self._connections:
                self._connections[session_id] = []
            self._connections[session_id].append(websocket)
            self._conn_to_session[connection_id] = session_id
            self._conn_to_ws[connection_id] = websocket
            self._last_pong[connection_id] = time.monotonic()

        await websocket.accept()

        logger.info(
            "WebSocket connection accepted",
            extra={
                "session_id": session_id,
                "connection_id": connection_id,
                "origin": origin,
                "action": "connect",
            },
        )

    async def disconnect(self, connection_id: str) -> None:
        """Remove a connection from all registries and log the disconnection.

        Looks up the ``session_id`` for the given ``connection_id``, removes
        the corresponding ``WebSocket`` from ``_connections[session_id]``, and
        cleans up the ``_conn_to_session``, ``_conn_to_ws``, and ``_last_pong``
        entries. If the session's connection list becomes empty, the session
        entry is also removed.

        This method is safe to call even if the ``connection_id`` is not
        currently registered (it will be a no-op in that case).

        Args:
            connection_id: The unique identifier of the connection to remove.
        """
        async with self._lock:
            session_id = self._conn_to_session.pop(connection_id, None)
            ws = self._conn_to_ws.pop(connection_id, None)
            self._last_pong.pop(connection_id, None)

            if session_id is not None and ws is not None:
                session_conns = self._connections.get(session_id, [])
                if ws in session_conns:
                    session_conns.remove(ws)
                if not session_conns:
                    self._connections.pop(session_id, None)

        logger.info(
            "WebSocket connection removed",
            extra={
                "connection_id": connection_id,
                "session_id": session_id,
                "action": "disconnect",
            },
        )

    async def broadcast_to_session(self, session_id: str, message: dict) -> None:
        """Send a JSON message to all active connections for a session.

        Iterates over all ``WebSocket`` objects registered under ``session_id``
        and sends the ``message`` as JSON. If a ``WebSocketDisconnect`` is raised
        for any individual connection, that connection is disconnected gracefully
        (via :meth:`disconnect`) and iteration continues for the remaining
        connections.

        Args:
            session_id: The proctoring session identifier.
            message: A JSON-serialisable dict to broadcast to all connections
                in the session.
        """
        # Take a snapshot of the connection list to avoid mutation during iteration
        async with self._lock:
            connections_snapshot = list(self._connections.get(session_id, []))
            # Build a reverse map: ws → connection_id for disconnect calls
            ws_to_conn_id: Dict[WebSocket, str] = {
                ws: cid for cid, ws in self._conn_to_ws.items()
            }

        for ws in connections_snapshot:
            conn_id = ws_to_conn_id.get(ws)
            try:
                await ws.send_json(message)
            except WebSocketDisconnect:
                logger.warning(
                    "WebSocket disconnected during broadcast",
                    extra={
                        "session_id": session_id,
                        "connection_id": conn_id,
                        "action": "broadcast_disconnect",
                    },
                )
                if conn_id:
                    await self.disconnect(conn_id)
            except Exception as exc:
                logger.error(
                    "Error broadcasting to WebSocket",
                    extra={
                        "session_id": session_id,
                        "connection_id": conn_id,
                        "error": str(exc),
                        "action": "broadcast_error",
                    },
                )
                if conn_id:
                    await self.disconnect(conn_id)

    async def send_to_connection(self, connection_id: str, message: dict) -> None:
        """Send a JSON message to a single connection identified by ``connection_id``.

        If the target connection is not found in the registry, the call is a
        no-op. If a ``WebSocketDisconnect`` is raised, the connection is
        removed via :meth:`disconnect`.

        Args:
            connection_id: The unique identifier of the target connection.
            message: A JSON-serialisable dict to send to the connection.
        """
        async with self._lock:
            ws = self._conn_to_ws.get(connection_id)

        if ws is None:
            logger.debug(
                "send_to_connection: connection not found",
                extra={"connection_id": connection_id},
            )
            return

        try:
            await ws.send_json(message)
        except WebSocketDisconnect:
            logger.warning(
                "WebSocket disconnected during send_to_connection",
                extra={"connection_id": connection_id, "action": "send_disconnect"},
            )
            await self.disconnect(connection_id)
        except Exception as exc:
            logger.error(
                "Error sending to WebSocket connection",
                extra={
                    "connection_id": connection_id,
                    "error": str(exc),
                    "action": "send_error",
                },
            )
            await self.disconnect(connection_id)

    def record_pong(self, connection_id: str) -> None:
        """Record the receipt of a pong response from a client.

        Updates the ``_last_pong`` timestamp for the given ``connection_id``
        to the current monotonic time. Called by the WebSocket router when a
        pong frame is received from the client.

        Args:
            connection_id: The unique identifier of the connection that sent
                the pong.
        """
        if connection_id in self._last_pong:
            self._last_pong[connection_id] = time.monotonic()

    async def start_heartbeat(self) -> None:
        """Run the heartbeat loop indefinitely as an asyncio coroutine.

        Every :data:`HEARTBEAT_INTERVAL_S` seconds (30 s), sends a ping
        message (``{"type": "ping"}``) to every active connection. After
        sending pings, waits :data:`PONG_TIMEOUT_S` seconds (10 s) and then
        disconnects any client whose ``_last_pong`` timestamp is older than
        ``HEARTBEAT_INTERVAL_S + PONG_TIMEOUT_S`` seconds ago (i.e. the
        client did not respond to the most recent ping within the timeout
        window).

        The coroutine runs until cancelled (e.g. during application shutdown).
        ``asyncio.CancelledError`` is allowed to propagate so the task can be
        cleanly cancelled.

        Heartbeat timeline per cycle::

            t=0   ─── sleep HEARTBEAT_INTERVAL_S ───►
            t=30  ─── send ping to all connections ──►
                  ─── sleep PONG_TIMEOUT_S ──────────►
            t=40  ─── disconnect silent clients ──────►
        """
        logger.info("WebSocket heartbeat started")
        while True:
            await asyncio.sleep(HEARTBEAT_INTERVAL_S)

            # Snapshot all current connection IDs and their WebSockets
            async with self._lock:
                conn_snapshot: Dict[str, WebSocket] = dict(self._conn_to_ws)

            ping_time = time.monotonic()

            # Send ping to all connections
            for conn_id, ws in conn_snapshot.items():
                try:
                    await ws.send_json({"type": "ping"})
                    logger.debug(
                        "Heartbeat ping sent",
                        extra={"connection_id": conn_id, "action": "ping"},
                    )
                except Exception as exc:
                    logger.warning(
                        "Failed to send heartbeat ping",
                        extra={"connection_id": conn_id, "error": str(exc)},
                    )

            # Wait for pong responses
            await asyncio.sleep(PONG_TIMEOUT_S)

            # Disconnect clients that haven't responded
            stale_connections: List[str] = []
            async with self._lock:
                for conn_id in list(conn_snapshot.keys()):
                    last_pong = self._last_pong.get(conn_id, 0.0)
                    if last_pong < ping_time:
                        stale_connections.append(conn_id)

            for conn_id in stale_connections:
                logger.warning(
                    "Disconnecting client: no pong received within timeout",
                    extra={
                        "connection_id": conn_id,
                        "pong_timeout_s": PONG_TIMEOUT_S,
                        "action": "heartbeat_timeout",
                    },
                )
                await self.disconnect(conn_id)

    def get_connection_count(self) -> int:
        """Return the total number of currently active WebSocket connections.

        Counts all individual ``WebSocket`` objects across all sessions by
        summing the lengths of each session's connection list.

        Returns:
            Total number of active connections as an integer.
        """
        return sum(len(conns) for conns in self._connections.values())

    def get_session_connection_count(self, session_id: str) -> int:
        """Return the number of active connections for a specific session.

        Args:
            session_id: The proctoring session identifier.

        Returns:
            Number of active connections for the session, or 0 if the session
            has no registered connections.
        """
        return len(self._connections.get(session_id, []))
